### ISSUE TITLE
Can't Launch

### ISSUE THREAD

**Issue by AlijahWise** [h1-mod/iw7-mod#112]
I'm trying to launch iw7-mod.exe, and i keep getting an error that says. "base adress was (00007FF674400000) and not (0000000140000000)"

**Comment by ComoSgt** [comment]
is it in the same folder as iw7-ship.exe? I think I tried replacing the ship.exe with a renamed mod.exe for experimental reasons and it threw that error.

**Comment by mjkzy** [comment]
bad game files or you're on a crack, we only support steam installs
