### ISSUE TITLE
cant launch dedi server 

### ISSUE THREAD

**Issue by justarandom777** [h1-mod/iw7-mod#117]
![image](https://github.com/Joelrau/iw7-mod/assets/134498847/3e224bbe-0514-41ab-88c8-638541091575)

**Comment by justarandom777** [comment]
> ![image](https://private-user-images.githubusercontent.com/134498847/303940922-3e224bbe-0514-41ab-88c8-638541091575.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzgwNDYsIm5iZiI6MTcwNzY3Nzc0NiwicGF0aCI6Ii8xMzQ0OTg4NDcvMzAzOTQwOTIyLTNlMjI0YmJlLTA1MTQtNDFhYi04OGM4LTYzODU0MTA5MTU3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQxODU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjNlNTRhMDYzZmM3OWQwODA0ZTIzNmIxZTU2MjVkMmFhNmE0ZDgyMzBkNTM2ZWJlNGVlMjU2YzBkY2UxOTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g6Q09TGfIhVZOs5-HG0lsHOE6XJS3l_2F4mlpKuoUbA)

What im doing wrong?

**Comment by mjkzy** [comment]
we're not done yet
